sudo: false
language: node_js
node_js: 7

cache: yarn
script: npm run test:travis

env:
  global:
    - CXX=g++-4.9
    - secure: "VDsxy30sE9ivdqoXkaKXo0czbS4brNpwKEIblu7f1gVLx7OD9pjTc78cdwrVbZDBYroSiYVYuUrLDjpVjH88lL/LxRrru3V0CIlAqqa+ssXcqycCaT/6ds+ZymuTTGRh+Mf12pIKO+yc8jTov2M7AzPJdpS+ORP5dImYyE3ex9s="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

deploy:
  - provider: script
    script: npm run gitpublish
    skip_cleanup: true
    on:
      branch: master
      repo: facebook/immutable-js
  - provider: script
    skip_cleanup: true
    script: npm run deploy
    on:
      branch: master
      repo: facebook/immutable-js
      tags: true
